language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION 'set scalaJSStage in Global := FastOptStage' test 'set scalaJSStage in Global := FullOptStage' test
scala:
  - 2.10.4
  - 2.11.5
jdk:
  - oraclejdk7
